export * from './heading/Heading'
export * from './paragraph/Paragraph'
export * from './paper/Paper'
export { Button as ButtonSecondary } from './buttons/button.secondary/Button'
export { Button as ButtonPrimary } from './buttons/button.primary/Button'
